# Generated by Django 3.0.6 on 2020-05-28 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200528_2216'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='country',
            unique_together={('name',)},
        ),
    ]
